// Auto-generated by scripts/scan-modules.js — do not edit manually
// Run `npm run scan:modules` or `npm run build` to regenerate

import type { Component } from 'vue'

export const componentKeyMap: Record<string, () => Promise<{ default: Component }>> = {
  'agent/index.vue': () => import('@modules/agent/frontend/index.vue'),
  'desktop-tools/index.vue': () => import('@modules/desktop-tools/frontend/index.vue'),
  'doc-viewer/index.vue': () => import('@modules/doc-viewer/frontend/index.vue'),
  'docs-open/index.vue': () => import('@modules/docs-open/frontend/index.vue'),
  'docx-parser/index.vue': () => import('@modules/docx-parser/frontend/index.vue'),
  'douyin-delivery/index.vue': () => import('@modules/douyin-delivery/frontend/index.vue'),
  'excel-engine/index.vue': () => import('@modules/excel-engine/frontend/index.vue'),
  'hello-world/index.vue': () => import('@modules/hello-world/frontend/index.vue'),
  'im/index.vue': () => import('@modules/im/frontend/index.vue'),
  'image-gen/index.vue': () => import('@modules/image-gen/frontend/index.vue'),
  'image-viewer/index.vue': () => import('@modules/image-viewer/frontend/index.vue'),
  'image-vision/index.vue': () => import('@modules/image-vision/frontend/index.vue'),
  'knowledge/index.vue': () => import('@modules/knowledge/frontend/index.vue'),
  'media-asr/index.vue': () => import('@modules/media-asr/frontend/index.vue'),
  'media-intelligence/index.vue': () => import('@modules/media-intelligence/frontend/index.vue'),
  'memory/index.vue': () => import('@modules/memory/frontend/index.vue'),
  'office-gen/index.vue': () => import('@modules/office-gen/frontend/index.vue'),
  'pdf-parser/index.vue': () => import('@modules/pdf-parser/frontend/index.vue'),
  'pdf-viewer/index.vue': () => import('@modules/pdf-viewer/frontend/index.vue'),
  'ppt-viewer/index.vue': () => import('@modules/ppt-viewer/frontend/index.vue'),
  'pptx-parser/index.vue': () => import('@modules/pptx-parser/frontend/index.vue'),
  'scheduler/index.vue': () => import('@modules/scheduler/frontend/index.vue'),
  'terminal-tools/index.vue': () => import('@modules/terminal-tools/frontend/index.vue'),
  'text-editor/index.vue': () => import('@modules/text-editor/frontend/index.vue'),
  'text-parser/index.vue': () => import('@modules/text-parser/frontend/index.vue'),
  'wechat-writer/index.vue': () => import('@modules/wechat-writer/frontend/index.vue'),
  'xlsx-parser/index.vue': () => import('@modules/xlsx-parser/frontend/index.vue'),
}
