// Auto-generated by scripts/scan-modules.js — do not edit manually
// Run `npm run scan:modules` or `npm run build` to regenerate

export const componentKeyMap: Record<string, () => Promise<{ default: any }>> = {
  'ai-assistant/index.vue': () => import('@modules/ai-assistant/frontend/index.vue'),
}
