import type { AppComponentLoader } from '@/platform/components/platform-app-loader'
import { createPlatformAppLoader } from '@/platform/components/platform-app-loader'

const platformAppDefinitions = [
  {
    componentKey: 'apps/core-system/index.vue',
    appKey: 'core-system',
    appName: '系统核心',
    routePrefix: '/api/system',
    status: 'platform',
    message: '平台基础能力入口已注册，当前承载系统信息、健康检查和框架级控制能力。',
  },
  {
    componentKey: 'apps/app-manager/index.vue',
    appKey: 'app-manager',
    appName: '应用管理器',
    routePrefix: '/api/app-manager',
    status: 'platform',
    message: '应用清单管理入口已注册，后续可以在这里查看和同步平台与模块应用。',
  },
  {
    componentKey: 'apps/dashboard/index.vue',
    appKey: 'dashboard',
    appName: '仪表盘',
    routePrefix: '/api/dashboard',
    status: 'platform',
    message: '系统概览入口已注册，当前先占位为框架级入口，后续可接入统计卡片和趋势图。',
  },
  {
    componentKey: 'apps/desktop/index.vue',
    appKey: 'desktop',
    appName: '文件管理',
    routePrefix: '/api/files',
    status: 'platform',
    message: '文件管理入口已注册，后续可接入文件树、列表、拖拽和预览面板。',
  },
  {
    componentKey: 'apps/recycle/index.vue',
    appKey: 'recycle',
    appName: '回收站',
    routePrefix: '/api/recycle',
    status: 'platform',
    message: '回收站入口已注册，后续可直接挂接回收站列表与恢复操作。',
  },
  {
    componentKey: 'apps/textEditor/index.vue',
    appKey: 'textEditor',
    appName: '文本编辑器',
    routePrefix: '/api/text-editor',
    status: 'platform',
    message: '文本编辑入口已注册，后续可接入文本和代码文件编辑器。',
  },
  {
    componentKey: 'apps/filePreview/index.vue',
    appKey: 'filePreview',
    appName: '文件预览',
    routePrefix: '/api/file-preview',
    status: 'platform',
    message: '文件预览入口已注册，后续可接入图片、PDF、音视频等只读预览能力。',
  },
  {
    componentKey: 'apps/file-toolbox/index.vue',
    appKey: 'file-toolbox',
    appName: '文件工具箱',
    routePrefix: '/api/file-toolbox',
    status: 'platform',
    message: '文件工具箱入口已注册，后续可接入文件批处理和快捷工具。',
  },
  {
    componentKey: 'apps/docxEditor/index.vue',
    appKey: 'docxEditor',
    appName: 'Word编辑器',
    routePrefix: '/api/word-editor',
    status: 'platform',
    message: 'Word 编辑入口已注册，后续可接入 docx 在线编辑能力。',
  },
  {
    componentKey: 'apps/office-workbench/index.vue',
    appKey: 'office-workbench',
    appName: 'Office工作台',
    routePrefix: '/api/office-workbench',
    status: 'platform',
    message: 'Office 工作台入口已注册，后续可作为 Office 相关能力的聚合页。',
  },
  {
    componentKey: 'apps/pptxEditor/index.vue',
    appKey: 'pptxEditor',
    appName: 'PPT编辑器',
    routePrefix: '/api/ppt-editor',
    status: 'platform',
    message: 'PPT 编辑入口已注册，后续可接入 pptx 在线编辑能力。',
  },
  {
    componentKey: 'apps/excelEditor/index.vue',
    appKey: 'excelEditor',
    appName: 'Excel编辑器',
    routePrefix: '/api/excel-editor',
    status: 'platform',
    message: 'Excel 编辑入口已注册，后续可接入 xlsx 在线编辑能力。',
  },
  {
    componentKey: 'apps/csvEditor/index.vue',
    appKey: 'csvEditor',
    appName: 'CSV编辑器',
    routePrefix: '/api/csv-editor',
    status: 'platform',
    message: 'CSV 编辑入口已注册，后续可接入 CSV/TSV 在线编辑能力。',
  },
  {
    componentKey: 'apps/user-admin/index.vue',
    appKey: 'user-admin',
    appName: '用户管理',
    routePrefix: '/api/user-management',
    status: 'platform',
    message: '用户管理入口已注册，后续可接入用户列表、创建和权限控制页面。',
  },
  {
    componentKey: 'apps/role-matrix/index.vue',
    appKey: 'role-matrix',
    appName: '角色权限',
    routePrefix: '/api/role-permissions',
    status: 'platform',
    message: '角色权限入口已注册，后续可接入角色矩阵和权限编辑页面。',
  },
  {
    componentKey: 'apps/system-config/index.vue',
    appKey: 'system-config',
    appName: '系统配置',
    routePrefix: '/api/system-config',
    status: 'platform',
    message: '系统配置入口已注册，后续可接入项目名、版本和登录页标题配置。',
  },
  {
    componentKey: 'apps/system-logs/index.vue',
    appKey: 'system-logs',
    appName: '系统日志',
    routePrefix: '/api/system-logs',
    status: 'platform',
    message: '系统日志入口已注册，后续可接入日志查询与筛选页面。',
  },
  {
    componentKey: 'apps/backup-restore/index.vue',
    appKey: 'backup-restore',
    appName: '备份恢复',
    routePrefix: '/api/backup',
    status: 'platform',
    message: '备份恢复入口已注册，后续可接入数据库备份与恢复页面。',
  },
  {
    componentKey: 'apps/system-status/index.vue',
    appKey: 'system-status',
    appName: '系统状态',
    routePrefix: '/api/system-status',
    status: 'platform',
    message: '系统状态入口已注册，后续可接入健康检查与运行状态面板。',
  },
  {
    componentKey: 'apps/feedback-center/index.vue',
    appKey: 'feedback-center',
    appName: '内测反馈',
    routePrefix: '/api/feedback',
    status: 'platform',
    message: '内测反馈入口已注册，后续可接入反馈列表和处理流转页面。',
  },
  {
    componentKey: 'apps/maintenance-center/index.vue',
    appKey: 'maintenance-center',
    appName: '运维诊断中心',
    routePrefix: '/api/ops-diagnostics',
    status: 'platform',
    message: '运维诊断入口已注册，后续可接入运维工具集合页面。',
  },
  {
    componentKey: 'apps/settings/index.vue',
    appKey: 'settings',
    appName: '设置',
    routePrefix: '/api/settings',
    status: 'platform',
    message: '设置入口已注册，后续可接入系统设置和用户/角色管理聚合页。',
  },
  {
    componentKey: 'apps/notification-center/index.vue',
    appKey: 'notification-center',
    appName: '通知中心',
    routePrefix: '/api/notifications',
    status: 'platform',
    message: '通知中心入口已注册，后续可接入通知列表、未读数和已读状态。',
  },
  {
    componentKey: 'apps/tasks/index.vue',
    appKey: 'tasks',
    appName: '我的任务',
    routePrefix: '/api/my-tasks',
    status: 'platform',
    message: '任务入口已注册，后续可接入个人任务列表和任务状态操作。',
  },
] as const

export const platformComponentKeyMap: Record<string, AppComponentLoader> = Object.fromEntries(
  platformAppDefinitions.map(item => [item.componentKey, createPlatformAppLoader({
    appKey: item.appKey,
    appName: item.appName,
    routePrefix: item.routePrefix,
    status: item.status,
    message: item.message,
  })]),
)

// Override desktop and recycle with real functional components
platformComponentKeyMap['apps/desktop/index.vue'] = () => import('@/platform/components/apps/desktop/index.vue')
platformComponentKeyMap['apps/recycle/index.vue'] = () => import('@/platform/components/apps/recycle/index.vue')
