"""FastAPI router for office-gen module.

Registers 8 cross-module capabilities:
  office-gen:docx   — generate Word from JSON
  office-gen:xlsx   — generate Excel from JSON
  office-gen:pptx   — generate PowerPoint from JSON
  office-gen:pdf    — generate PDF from JSON
  office-gen:convert — convert between office formats
  office-gen:generate_to_artifact — generate and return as artifact (no file conflict)
  office-gen:replace_existing — generate and replace an existing file
  office-gen:export_to_artifact — convert existing file to artifact
"""
import io
import logging
import os

from app.core.exceptions import ValidationError
from app.database import AsyncSessionLocal
from app.middleware.auth import require_permission
from app.models.user import User
from app.schemas.common import ApiResponse
from app.services.artifact_service import create_artifact
from app.services.file_reader import get_file_content_bytes, read_uploaded_file, resolve_caller_user_id
from app.services.file_upload_service import replace_file_content, upload_file
from app.services.module_registry import register_capability
from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field

from . import converter, generator

logger = logging.getLogger("v2.office-gen").getChild("router")

router = APIRouter(prefix="/api/office-gen", tags=["office-gen"])


# ── Helper: persist generated bytes via framework file_upload_service ──

SUPPORTED_GENERATE_FORMATS = {"docx", "xlsx", "pptx", "pdf"}


def _normalize_format(format_type: object) -> str:
    fmt = str(format_type or "").lower().lstrip(".").strip()
    if fmt not in SUPPORTED_GENERATE_FORMATS:
        raise ValidationError(f"Unsupported format: {fmt or '<empty>'}")
    return fmt


def _normalize_convert_format(format_type: object) -> str:
    fmt = str(format_type or "").lower().lstrip(".").strip()
    if not fmt:
        raise ValidationError("target_format is required")
    if fmt not in converter.SUPPORTED_FORMATS:
        supported = ", ".join(sorted(converter.SUPPORTED_FORMATS))
        raise ValidationError(f"Unsupported target_format: {fmt}. Supported: {supported}")
    return fmt


def _positive_int(value: object, name: str) -> int:
    if isinstance(value, bool):
        raise ValidationError(f"{name} must be a positive integer")
    try:
        parsed = int(value)
    except (TypeError, ValueError) as exc:
        raise ValidationError(f"{name} must be a positive integer") from exc
    if parsed <= 0:
        raise ValidationError(f"{name} must be a positive integer")
    return parsed


def _optional_positive_int(value: object, name: str) -> int | None:
    if value is None or value == "":
        return None
    return _positive_int(value, name)


def _require_non_empty_list(params: dict, key: str, aliases: tuple[str, ...] = ()) -> list:
    for candidate in (key, *aliases):
        value = params.get(candidate)
        if isinstance(value, list) and value:
            return value
        content_ir = params.get("content_ir")
        if isinstance(content_ir, dict):
            value = content_ir.get(candidate)
            if isinstance(value, list) and value:
                return value
    raise ValidationError(f"{key} must be a non-empty array")


def _render_generated_bytes(render) -> bytes:
    try:
        return render()
    except (RuntimeError, ValueError) as exc:
        raise ValidationError(str(exc)) from exc


def _generate_bytes_for_format(format_type: str, filename: str, params: dict) -> bytes:
    fmt = _normalize_format(format_type)
    if fmt == "xlsx":
        sheets = _require_non_empty_list(params, "sheets", ("工作表", "blocks"))
        return _render_generated_bytes(lambda: generator.generate_xlsx({"filename": filename, "sheets": sheets}))
    if fmt == "docx":
        content = _require_non_empty_list(params, "content", ("blocks",))
        return _render_generated_bytes(lambda: generator.generate_docx({"filename": filename, "content": content}))
    if fmt == "pptx":
        slides = _require_non_empty_list(params, "slides", ("幻灯片", "blocks"))
        return _render_generated_bytes(lambda: generator.generate_pptx({"filename": filename, "slides": slides}))
    content = _require_non_empty_list(params, "content", ("blocks",))
    return _render_generated_bytes(lambda: generator.generate_pdf({"filename": filename, "content": content}))


async def _ensure_content_package(
    file_id: int,
    owner_id: int,
    caller: str,
    *,
    origin_type: str = "generated",
    db=None,
) -> dict:
    """Best-effort Content Package sync with explicit status in the response."""
    package_id: int | None = None
    owns_session = db is None
    if owns_session:
        db_cm = AsyncSessionLocal()
        db = await db_cm.__aenter__()
    else:
        db_cm = None
    try:
        from app.services.content.package_service import ContentPackageService
        from app.services.content.pipeline_service import ContentPipelineService

        pkg_svc = ContentPackageService()
        pipeline_svc = ContentPipelineService()
        pkg = await pkg_svc.get_or_create(db, file_id, owner_id, caller, origin_type=origin_type)
        package_id = int(pkg["id"])
        result = await pipeline_svc.run_pipeline_for_package(db, pkg["id"], caller)
        return {
            "content_package_id": package_id,
            "content_package_status": result.get("status", pkg.get("status", "unknown")),
            "content_package_error": None,
        }
    except Exception as e:
        logger.warning("Content Package sync failed for file_id=%s: %s", file_id, e)
        return {
            "content_package_id": package_id,
            "content_package_status": "failed",
            "content_package_error": str(e),
        }
    finally:
        if owns_session and db_cm is not None:
            await db_cm.__aexit__(None, None, None)


async def _find_accessible_content_package(db, file_id: int, owner_id: int) -> int | None:
    try:
        from app.services.content.package_service import ContentPackageService

        pkg = await ContentPackageService().get_package(db, file_id=file_id, owner_id=owner_id)
        return int(pkg["id"])
    except Exception:
        return None


async def _save_file_bytes(
    content: bytes,
    filename: str,
    extension: str,
    owner_id: int,
    folder_id: int | None = None,
) -> dict:
    """Save generated bytes via framework file_upload_service (content-addressed)."""
    ext = extension.lower().lstrip(".")
    final_name = f"{filename}.{ext}"

    async with AsyncSessionLocal() as db:
        result = await upload_file(
            db,
            io.BytesIO(content),
            final_name,
            owner_id,
            folder_id,
        )

    return {
        "file_id": result["id"],
        "name": result["name"],
        "extension": result["extension"],
        "size": result["size"],
        "mime_type": result["mime_type"],
        "storage_path": "",
        "deduplicated": result.get("deduplicated", False),
    }


async def _save_to_artifact(
    content: bytes,
    filename: str,
    extension: str,
    owner_id: int,
    folder_id: int | None = None,
) -> dict:
    """Save generated bytes as an artifact (avoids file-name conflicts)."""
    ext = extension.lower().lstrip(".")
    async with AsyncSessionLocal() as db:
        artifact = await create_artifact(
            db, owner_id,
            name=filename,
            extension=ext,
            content=content,
            folder_id=folder_id,
            source_module="office-gen",
            conflict_policy="create_version",
        )
    return artifact


# =====================================================================
# Capability: office-gen:docx
# =====================================================================
async def _cap_docx(params: dict, caller: str) -> dict:
    owner_id = resolve_caller_user_id(caller)
    filename = params.get("filename", "未命名文档")
    content = _require_non_empty_list(params, "content", ("blocks",))
    folder_id = _optional_positive_int(params.get("folder_id"), "folder_id")

    data = {"filename": filename, "content": content}
    bytes_data = _render_generated_bytes(lambda: generator.generate_docx(data))
    result = await _save_file_bytes(bytes_data, filename, "docx", owner_id, folder_id)
    return result


# =====================================================================
# Capability: office-gen:xlsx
# =====================================================================
async def _cap_xlsx(params: dict, caller: str) -> dict:
    owner_id = resolve_caller_user_id(caller)
    filename = params.get("filename", "未命名表格")
    sheets = _require_non_empty_list(params, "sheets", ("工作表", "blocks"))
    folder_id = _optional_positive_int(params.get("folder_id"), "folder_id")

    data = {"filename": filename, "sheets": sheets}
    bytes_data = _render_generated_bytes(lambda: generator.generate_xlsx(data))
    result = await _save_file_bytes(bytes_data, filename, "xlsx", owner_id, folder_id)
    return result


# =====================================================================
# Capability: office-gen:pptx
# =====================================================================
async def _cap_pptx(params: dict, caller: str) -> dict:
    owner_id = resolve_caller_user_id(caller)
    filename = params.get("filename", "未命名演示")
    slides = _require_non_empty_list(params, "slides", ("幻灯片", "blocks"))
    folder_id = _optional_positive_int(params.get("folder_id"), "folder_id")

    data = {"filename": filename, "slides": slides}
    bytes_data = _render_generated_bytes(lambda: generator.generate_pptx(data))
    result = await _save_file_bytes(bytes_data, filename, "pptx", owner_id, folder_id)
    return result


# =====================================================================
# Capability: office-gen:pdf
# =====================================================================
async def _cap_pdf(params: dict, caller: str) -> dict:
    owner_id = resolve_caller_user_id(caller)
    filename = params.get("filename", "未命名文档")
    content = _require_non_empty_list(params, "content", ("blocks",))
    folder_id = _optional_positive_int(params.get("folder_id"), "folder_id")

    data = {"filename": filename, "content": content}
    bytes_data = _render_generated_bytes(lambda: generator.generate_pdf(data))
    result = await _save_file_bytes(bytes_data, filename, "pdf", owner_id, folder_id)
    return result


# =====================================================================
# Capability: office-gen:convert
# =====================================================================
async def _cap_convert(params: dict, caller: str) -> dict:
    owner_id = resolve_caller_user_id(caller)
    file_id = _positive_int(params.get("file_id"), "file_id")
    target_format = _normalize_convert_format(params.get("target_format", "pdf"))

    async with AsyncSessionLocal() as db:
        _, source_path, _ = await read_uploaded_file(
            db,
            file_id,
            owner_id,
            converter.SUPPORTED_FORMATS,
        )

        try:
            output_name, output_bytes = await converter.convert_by_file_id(
                str(source_path), target_format
            )
        except (FileNotFoundError, RuntimeError, TimeoutError, ValueError) as exc:
            raise ValidationError(str(exc)) from exc

    result = await _save_file_bytes(
        output_bytes,
        os.path.splitext(output_name)[0],
        target_format,
        owner_id,
    )
    return result


# =====================================================================
# Register capabilities with framework
# =====================================================================

register_capability(
    "office-gen", "docx", _cap_docx,
    brief="生成 Word 文档",
    description="Generate a Word (.docx) document from structured JSON and save to file system. "
                "Content blocks: {type: 标题|段落|表格|图片, text, level, bold, align, header, rows}",
    parameters={
        "type": "object",
        "properties": {
            "filename": {"type": "string", "description": "Output file name (without extension)", "default": "未命名文档"},
            "content": {
                "type": "array",
                "description": "Array of content blocks",
                "items": {
                    "type": "object",
                    "properties": {
                        "type": {"type": "string", "description": "Block type: 标题|段落|表格|图片"},
                        "text": {"type": "string", "description": "Text content (for 标题/段落)"},
                        "level": {"type": "integer", "description": "Heading level 1-4 (for 标题)", "default": 1},
                        "bold": {"type": "boolean", "description": "Bold text (for 段落)", "default": False},
                        "align": {"type": "string", "description": "Alignment: left|center|right|justify", "default": "left"},
                        "header": {"type": "array", "description": "Table header row (for 表格)"},
                        "rows": {"type": "array", "description": "Table data rows (for 表格)"},
                    },
                },
            },
            "blocks": {"type": "array", "description": "Content IR block alias for content"},
            "content_ir": {"type": "object", "description": "Content IR object with non-empty blocks"},
            "folder_id": {"type": "integer", "description": "Target folder ID (optional, root if omitted)"},
        },
        "required": ["filename"],
    },
    min_role="editor",
)

register_capability(
    "office-gen", "xlsx", _cap_xlsx,
    brief="生成 Excel 表格",
    description="Generate an Excel (.xlsx) spreadsheet from structured JSON and save to file system. "
                "Sheets: {name, columns, rows}",
    parameters={
        "type": "object",
        "properties": {
            "filename": {"type": "string", "description": "Output file name (without extension)", "default": "未命名表格"},
            "sheets": {
                "type": "array",
                "description": "Array of sheet objects",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string", "description": "Sheet tab name"},
                        "columns": {"type": "array", "description": "Header column names"},
                        "rows": {"type": "array", "description": "Data rows (each row is an array of cell values)"},
                    },
                },
            },
            "blocks": {"type": "array", "description": "Content IR sheet block alias for sheets"},
            "content_ir": {"type": "object", "description": "Spreadsheet Content IR object with non-empty blocks"},
            "folder_id": {"type": "integer", "description": "Target folder ID (optional)"},
        },
        "required": ["filename"],
    },
    min_role="editor",
)

register_capability(
    "office-gen", "pptx", _cap_pptx,
    brief="生成 PPT 演示文稿",
    description="Generate a PowerPoint (.pptx) presentation from structured JSON and save to file system. "
                "Slides: {title, bullets, notes}",
    parameters={
        "type": "object",
        "properties": {
            "filename": {"type": "string", "description": "Output file name (without extension)", "default": "未命名演示"},
            "slides": {
                "type": "array",
                "description": "Array of slide objects",
                "items": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string", "description": "Slide title"},
                        "bullets": {"type": "array", "description": "Bullet point strings or {text, level} objects"},
                        "notes": {"type": "string", "description": "Speaker notes"},
                    },
                },
            },
            "blocks": {"type": "array", "description": "Content IR slide block alias for slides"},
            "content_ir": {"type": "object", "description": "Presentation Content IR object with non-empty blocks"},
            "folder_id": {"type": "integer", "description": "Target folder ID (optional)"},
        },
        "required": ["filename"],
    },
    min_role="editor",
)

register_capability(
    "office-gen", "pdf", _cap_pdf,
    brief="生成 PDF 文档",
    description="Generate a PDF document from structured JSON (same schema as docx) and save to file system. "
                "Alternatively generate docx first then convert via office-gen:convert for better layout.",
    parameters={
        "type": "object",
        "properties": {
            "filename": {"type": "string", "description": "Output file name (without extension)", "default": "未命名文档"},
            "content": {
                "type": "array",
                "description": "Array of content blocks (same structure as docx content)",
                "items": {
                    "type": "object",
                    "properties": {
                        "type": {"type": "string", "description": "Block type: 标题|段落|表格|分页"},
                        "text": {"type": "string", "description": "Text content"},
                        "level": {"type": "integer", "description": "Heading level 1-4", "default": 1},
                        "bold": {"type": "boolean", "description": "Bold text", "default": False},
                        "align": {"type": "string", "description": "Alignment", "default": "left"},
                    },
                },
            },
            "blocks": {"type": "array", "description": "Content IR block alias for content"},
            "content_ir": {"type": "object", "description": "Document Content IR object with non-empty blocks"},
            "folder_id": {"type": "integer", "description": "Target folder ID (optional)"},
        },
        "required": ["filename"],
    },
    min_role="editor",
)

register_capability(
    "office-gen", "convert", _cap_convert,
    brief="转换办公文档格式",
    description="Convert an existing office file from one format to another using LibreOffice. "
                "Supports: pdf, docx, pptx, xlsx, odt, html, png, etc. Requires LibreOffice installed.",
    parameters={
        "type": "object",
        "properties": {
            "file_id": {"type": "integer", "description": "Source file ID in the file storage system"},
            "target_format": {
                "type": "string",
                "description": "Target format: pdf, docx, pptx, xlsx, png, jpg, html, txt, csv, etc.",
                "default": "pdf",
            },
        },
        "required": ["file_id"],
    },
    min_role="editor",
)

# =====================================================================
# Capability: office-gen:generate_to_artifact
# Generate Office file and return as artifact (avoids file-name conflicts)
# =====================================================================
async def _cap_generate_to_artifact(params: dict, caller: str) -> dict:
    """Generate an office file and return as an artifact record.
    No file-name conflict: artifacts support create_version mode by default.
    """
    owner_id = resolve_caller_user_id(caller)
    format_type = _normalize_format(params.get("format", "xlsx"))
    filename = params.get("filename", "未命名文档")
    folder_id = _optional_positive_int(params.get("folder_id"), "folder_id")

    bytes_data = _generate_bytes_for_format(format_type, filename, params)

    artifact = await _save_to_artifact(bytes_data, filename, format_type, owner_id, folder_id)
    artifact_file_id = artifact.get("file_id")
    if not artifact_file_id:
        raise RuntimeError("Artifact was created without a file_id")

    package_state = await _ensure_content_package(
        int(artifact_file_id),
        owner_id,
        caller,
        origin_type="generated",
    )

    return {
        "artifact_id": artifact["id"],
        "file_id": artifact.get("file_id"),
        **package_state,
        "format": format_type,
        "name": artifact["name"],
        "extension": artifact["extension"],
        "size": artifact["size"],
        "status": "created",
    }


# =====================================================================
# Capability: office-gen:replace_existing
# Generate Office file and replace an existing file entry
# =====================================================================
async def _cap_replace_existing(params: dict, caller: str) -> dict:
    """Generate an office file and replace an existing file entry.
    No base64 needed — system handles binary internally.
    Returns updated file info with version tracking.
    """
    owner_id = resolve_caller_user_id(caller)
    format_type = _normalize_format(params.get("format", "xlsx"))
    filename = params.get("filename", "未命名文档")
    target_file_id = _positive_int(params.get("target_file_id"), "target_file_id")

    bytes_data = _generate_bytes_for_format(format_type, filename, params)

    async with AsyncSessionLocal() as db:
        result = await replace_file_content(db, target_file_id, owner_id, bytes_data)

        package_state = await _ensure_content_package(
            target_file_id,
            owner_id,
            caller,
            origin_type="generated",
            db=db,
        )

    return {
        "file_id": target_file_id,
        **package_state,
        "name": result["name"],
        "size": result["size"],
        "format": format_type,
        "status": "replaced",
    }


# =====================================================================
# Capability: office-gen:export_to_artifact
# Convert an existing file to an artifact
# =====================================================================
async def _cap_export_to_artifact(params: dict, caller: str) -> dict:
    """Export an existing office file as an artifact record for version management."""
    owner_id = resolve_caller_user_id(caller)
    file_id = _positive_int(params.get("file_id"), "file_id")

    async with AsyncSessionLocal() as db:
        from app.services.file_service import check_file_access

        file = await check_file_access(db, file_id, owner_id)
        content_package_id = await _find_accessible_content_package(db, file_id, owner_id)

    content_bytes = await get_file_content_bytes(file_id, owner_id)

    async with AsyncSessionLocal() as db:
        artifact = await create_artifact(
            db, owner_id,
            name=file.name,
            extension=file.extension or "",
            content=content_bytes,
            folder_id=file.folder_id,
            source_module="office-gen",
            source_object_type="content_package" if content_package_id else "file",
            source_object_id=content_package_id or file_id,
            file_id=file_id,
            conflict_policy="create_version",
        )

    return {
        "artifact_id": artifact["id"],
        "file_id": file_id,
        "content_package_id": content_package_id,
        "name": artifact["name"],
        "extension": artifact["extension"],
        "size": artifact["size"],
    }


# =====================================================================
# Register new capabilities
# =====================================================================

register_capability(
    "office-gen", "generate_to_artifact", _cap_generate_to_artifact,
    brief="生成办公文档并返回制品",
    description="Generate an office file and return as an artifact (no file-name conflict). "
                "Supports xlsx/docx/pptx/pdf.",
    parameters={
        "type": "object",
        "properties": {
            "format": {"type": "string", "description": "Output format: xlsx/docx/pptx/pdf", "default": "xlsx"},
            "filename": {"type": "string", "description": "Output file name (without extension)", "default": "未命名文档"},
            "sheets": {"type": "array", "description": "Sheets array (for xlsx)"},
            "content": {"type": "array", "description": "Content blocks (for docx/pdf)"},
            "slides": {"type": "array", "description": "Slides array (for pptx)"},
            "blocks": {"type": "array", "description": "Content IR blocks alias for the chosen format"},
            "content_ir": {"type": "object", "description": "Content IR object with non-empty blocks"},
            "folder_id": {"type": "integer", "description": "Target folder ID (optional)"},
        },
        "required": ["format", "filename"],
    },
    min_role="editor",
)

register_capability(
    "office-gen", "replace_existing", _cap_replace_existing,
    brief="生成办公文档并替换已有文件",
    description="Generate an office file and replace an existing file entry. No base64 needed.",
    parameters={
        "type": "object",
        "properties": {
            "format": {"type": "string", "description": "Output format: xlsx/docx/pptx/pdf", "default": "xlsx"},
            "filename": {"type": "string", "description": "Output file name", "default": "未命名文档"},
            "target_file_id": {"type": "integer", "description": "Existing file ID to replace"},
            "sheets": {"type": "array", "description": "Sheets array (for xlsx)"},
            "content": {"type": "array", "description": "Content blocks (for docx/pdf)"},
            "slides": {"type": "array", "description": "Slides array (for pptx)"},
            "blocks": {"type": "array", "description": "Content IR blocks alias for the chosen format"},
            "content_ir": {"type": "object", "description": "Content IR object with non-empty blocks"},
        },
        "required": ["format", "target_file_id"],
    },
    min_role="editor",
)

register_capability(
    "office-gen", "export_to_artifact", _cap_export_to_artifact,
    brief="导出已有文件为制品",
    description="Export an existing office file as an artifact for version management.",
    parameters={
        "type": "object",
        "properties": {
            "file_id": {"type": "integer", "description": "Existing file ID to export"},
        },
        "required": ["file_id"],
    },
    min_role="editor",
)


# =====================================================================
# HTTP endpoints (for direct testing / sandbox)
# =====================================================================

class GenerateDocxRequest(BaseModel):
    filename: str = "未命名文档"
    content: list = Field(default_factory=list)
    blocks: list = Field(default_factory=list)
    content_ir: dict | None = None
    folder_id: int | None = None


class GenerateXlsxRequest(BaseModel):
    filename: str = "未命名表格"
    sheets: list = Field(default_factory=list)
    blocks: list = Field(default_factory=list)
    content_ir: dict | None = None
    folder_id: int | None = None


class GeneratePptxRequest(BaseModel):
    filename: str = "未命名演示"
    slides: list = Field(default_factory=list)
    blocks: list = Field(default_factory=list)
    content_ir: dict | None = None
    folder_id: int | None = None


class GeneratePdfRequest(BaseModel):
    filename: str = "未命名文档"
    content: list = Field(default_factory=list)
    blocks: list = Field(default_factory=list)
    content_ir: dict | None = None
    folder_id: int | None = None


class ConvertRequest(BaseModel):
    file_id: int
    target_format: str = "pdf"


@router.get("/health")
async def health():
    return ApiResponse(data={"module": "office-gen", "status": "ok",
                             "libreoffice": converter.check_libreoffice() is not None})


@router.post("/docx")
async def http_generate_docx(
    body: GenerateDocxRequest,
    user: User = Depends(require_permission("editor")),
):
    result = await _cap_docx(body.model_dump(), f"user:{user.id}")
    return ApiResponse(data=result)


@router.post("/xlsx")
async def http_generate_xlsx(
    body: GenerateXlsxRequest,
    user: User = Depends(require_permission("editor")),
):
    result = await _cap_xlsx(body.model_dump(), f"user:{user.id}")
    return ApiResponse(data=result)


@router.post("/pptx")
async def http_generate_pptx(
    body: GeneratePptxRequest,
    user: User = Depends(require_permission("editor")),
):
    result = await _cap_pptx(body.model_dump(), f"user:{user.id}")
    return ApiResponse(data=result)


@router.post("/pdf")
async def http_generate_pdf(
    body: GeneratePdfRequest,
    user: User = Depends(require_permission("editor")),
):
    result = await _cap_pdf(body.model_dump(), f"user:{user.id}")
    return ApiResponse(data=result)


@router.post("/convert")
async def http_convert(
    body: ConvertRequest,
    user: User = Depends(require_permission("editor")),
):
    result = await _cap_convert(body.model_dump(), f"user:{user.id}")
    return ApiResponse(data=result)
