"""FastAPI router for office-gen module.

Registers 5 cross-module capabilities:
  office-gen:docx   — generate Word from JSON
  office-gen:xlsx   — generate Excel from JSON
  office-gen:pptx   — generate PowerPoint from JSON
  office-gen:pdf    — generate PDF from JSON
  office-gen:convert — convert between office formats
"""
import hashlib
import io
import logging
import os
from pathlib import Path

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db, AsyncSessionLocal
from app.middleware.auth import require_permission
from app.models.user import User
from app.schemas.common import ApiResponse
from app.services.module_registry import register_capability
from app.config import get_settings
from app.services.file_upload_service import upload_file

from . import converter
from . import generator

logger = logging.getLogger("v2.office-gen").getChild("router")

router = APIRouter(prefix="/api/office-gen", tags=["office-gen"])

UPLOAD_ROOT = Path(get_settings().UPLOAD_DIR).resolve()


# ── Helper: persist generated bytes via framework file_upload_service ──

async def _save_file_bytes(
    content: bytes,
    filename: str,
    extension: str,
    owner_id: int,
    folder_id: int | None = None,
) -> dict:
    """Save generated bytes via framework file_upload_service (content-addressed)."""
    ext = extension.lower().lstrip(".")
    final_name = f"{filename}.{ext}"

    async with AsyncSessionLocal() as db:
        result = await upload_file(
            db,
            io.BytesIO(content),
            final_name,
            owner_id,
            folder_id,
        )

    return {
        "file_id": result["id"],
        "name": result["name"],
        "extension": result["extension"],
        "size": result["size"],
        "mime_type": result["mime_type"],
        "storage_path": "",
        "deduplicated": result.get("deduplicated", False),
    }


def _resolve_user_id(caller: str) -> int:
    if caller.startswith("user:"):
        return int(caller.split(":", 1)[1])
    raise ValueError(f"Unknown caller format: {caller}")


# =====================================================================
# Capability: office-gen:docx
# =====================================================================
async def _cap_docx(params: dict, caller: str) -> dict:
    owner_id = _resolve_user_id(caller)
    filename = params.get("filename", "未命名文档")
    content = params.get("content", [])
    folder_id = params.get("folder_id")

    data = {"filename": filename, "content": content}
    bytes_data = generator.generate_docx(data)
    result = await _save_file_bytes(bytes_data, filename, "docx", owner_id, folder_id)
    return result


# =====================================================================
# Capability: office-gen:xlsx
# =====================================================================
async def _cap_xlsx(params: dict, caller: str) -> dict:
    owner_id = _resolve_user_id(caller)
    filename = params.get("filename", "未命名表格")
    sheets = params.get("sheets", []) or params.get("工作表", [])
    folder_id = params.get("folder_id")

    data = {"filename": filename, "sheets": sheets}
    bytes_data = generator.generate_xlsx(data)
    result = await _save_file_bytes(bytes_data, filename, "xlsx", owner_id, folder_id)
    return result


# =====================================================================
# Capability: office-gen:pptx
# =====================================================================
async def _cap_pptx(params: dict, caller: str) -> dict:
    owner_id = _resolve_user_id(caller)
    filename = params.get("filename", "未命名演示")
    slides = params.get("slides", []) or params.get("幻灯片", [])
    folder_id = params.get("folder_id")

    data = {"filename": filename, "slides": slides}
    bytes_data = generator.generate_pptx(data)
    result = await _save_file_bytes(bytes_data, filename, "pptx", owner_id, folder_id)
    return result


# =====================================================================
# Capability: office-gen:pdf
# =====================================================================
async def _cap_pdf(params: dict, caller: str) -> dict:
    owner_id = _resolve_user_id(caller)
    filename = params.get("filename", "未命名文档")
    content = params.get("content", [])
    folder_id = params.get("folder_id")

    data = {"filename": filename, "content": content}
    bytes_data = generator.generate_pdf(data)
    result = await _save_file_bytes(bytes_data, filename, "pdf", owner_id, folder_id)
    return result


# =====================================================================
# Capability: office-gen:convert
# =====================================================================
async def _cap_convert(params: dict, caller: str) -> dict:
    owner_id = _resolve_user_id(caller)
    file_id = params.get("file_id")
    target_format = params.get("target_format", "pdf")

    if not file_id:
        raise ValueError("file_id is required")

    from app.services.file_service import check_file_access

    async with AsyncSessionLocal() as db:
        file_record = await check_file_access(db, file_id, owner_id)
        source_path = str(UPLOAD_ROOT / file_record.storage_path)
        if not os.path.exists(source_path):
            raise FileNotFoundError(f"File not found on disk: {source_path}")

        output_name, output_bytes = await converter.convert_by_file_id(
            source_path, target_format
        )

    out_ext = target_format.lower().lstrip(".")
    result = await _save_file_bytes(
        output_bytes,
        os.path.splitext(output_name)[0],
        out_ext,
        owner_id,
    )
    return result


# =====================================================================
# Register capabilities with framework
# =====================================================================

register_capability(
    "office-gen", "docx", _cap_docx,
    brief="生成 Word 文档",
    description="Generate a Word (.docx) document from structured JSON and save to file system. "
                "Content blocks: {type: 标题|段落|表格|图片, text, level, bold, align, header, rows}",
    parameters={
        "type": "object",
        "properties": {
            "filename": {"type": "string", "description": "Output file name (without extension)", "default": "未命名文档"},
            "content": {
                "type": "array",
                "description": "Array of content blocks",
                "items": {
                    "type": "object",
                    "properties": {
                        "type": {"type": "string", "description": "Block type: 标题|段落|表格|图片"},
                        "text": {"type": "string", "description": "Text content (for 标题/段落)"},
                        "level": {"type": "integer", "description": "Heading level 1-4 (for 标题)", "default": 1},
                        "bold": {"type": "boolean", "description": "Bold text (for 段落)", "default": False},
                        "align": {"type": "string", "description": "Alignment: left|center|right|justify", "default": "left"},
                        "header": {"type": "array", "description": "Table header row (for 表格)"},
                        "rows": {"type": "array", "description": "Table data rows (for 表格)"},
                    },
                },
            },
            "folder_id": {"type": "integer", "description": "Target folder ID (optional, root if omitted)"},
        },
        "required": ["filename", "content"],
    },
    min_role="editor",
)

register_capability(
    "office-gen", "xlsx", _cap_xlsx,
    brief="生成 Excel 表格",
    description="Generate an Excel (.xlsx) spreadsheet from structured JSON and save to file system. "
                "Sheets: {name, columns, rows}",
    parameters={
        "type": "object",
        "properties": {
            "filename": {"type": "string", "description": "Output file name (without extension)", "default": "未命名表格"},
            "sheets": {
                "type": "array",
                "description": "Array of sheet objects",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string", "description": "Sheet tab name"},
                        "columns": {"type": "array", "description": "Header column names"},
                        "rows": {"type": "array", "description": "Data rows (each row is an array of cell values)"},
                    },
                },
            },
            "folder_id": {"type": "integer", "description": "Target folder ID (optional)"},
        },
        "required": ["filename", "sheets"],
    },
    min_role="editor",
)

register_capability(
    "office-gen", "pptx", _cap_pptx,
    brief="生成 PPT 演示文稿",
    description="Generate a PowerPoint (.pptx) presentation from structured JSON and save to file system. "
                "Slides: {title, bullets, notes}",
    parameters={
        "type": "object",
        "properties": {
            "filename": {"type": "string", "description": "Output file name (without extension)", "default": "未命名演示"},
            "slides": {
                "type": "array",
                "description": "Array of slide objects",
                "items": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string", "description": "Slide title"},
                        "bullets": {"type": "array", "description": "Bullet point strings or {text, level} objects"},
                        "notes": {"type": "string", "description": "Speaker notes"},
                    },
                },
            },
            "folder_id": {"type": "integer", "description": "Target folder ID (optional)"},
        },
        "required": ["filename", "slides"],
    },
    min_role="editor",
)

register_capability(
    "office-gen", "pdf", _cap_pdf,
    brief="生成 PDF 文档",
    description="Generate a PDF document from structured JSON (same schema as docx) and save to file system. "
                "Alternatively generate docx first then convert via office-gen:convert for better layout.",
    parameters={
        "type": "object",
        "properties": {
            "filename": {"type": "string", "description": "Output file name (without extension)", "default": "未命名文档"},
            "content": {
                "type": "array",
                "description": "Array of content blocks (same structure as docx content)",
                "items": {
                    "type": "object",
                    "properties": {
                        "type": {"type": "string", "description": "Block type: 标题|段落|表格|分页"},
                        "text": {"type": "string", "description": "Text content"},
                        "level": {"type": "integer", "description": "Heading level 1-4", "default": 1},
                        "bold": {"type": "boolean", "description": "Bold text", "default": False},
                        "align": {"type": "string", "description": "Alignment", "default": "left"},
                    },
                },
            },
            "folder_id": {"type": "integer", "description": "Target folder ID (optional)"},
        },
        "required": ["filename", "content"],
    },
    min_role="editor",
)

register_capability(
    "office-gen", "convert", _cap_convert,
    brief="转换办公文档格式",
    description="Convert an existing office file from one format to another using LibreOffice. "
                "Supports: pdf, docx, pptx, xlsx, odt, html, png, etc. Requires LibreOffice installed.",
    parameters={
        "type": "object",
        "properties": {
            "file_id": {"type": "integer", "description": "Source file ID in the file storage system"},
            "target_format": {
                "type": "string",
                "description": "Target format: pdf, docx, pptx, xlsx, png, jpg, html, txt, csv, etc.",
                "default": "pdf",
            },
        },
        "required": ["file_id"],
    },
    min_role="editor",
)


# =====================================================================
# HTTP endpoints (for direct testing / sandbox)
# =====================================================================

class GenerateDocxRequest(BaseModel):
    filename: str = "未命名文档"
    content: list = []
    folder_id: int | None = None


class GenerateXlsxRequest(BaseModel):
    filename: str = "未命名表格"
    sheets: list = []
    folder_id: int | None = None


class GeneratePptxRequest(BaseModel):
    filename: str = "未命名演示"
    slides: list = []
    folder_id: int | None = None


class GeneratePdfRequest(BaseModel):
    filename: str = "未命名文档"
    content: list = []
    folder_id: int | None = None


class ConvertRequest(BaseModel):
    file_id: int
    target_format: str = "pdf"


@router.get("/health")
async def health():
    return ApiResponse(data={"module": "office-gen", "status": "ok",
                             "libreoffice": converter.check_libreoffice() is not None})


@router.post("/docx")
async def http_generate_docx(
    body: GenerateDocxRequest,
    user: User = Depends(require_permission("editor")),
):
    result = await _cap_docx(body.model_dump(), f"user:{user.id}")
    return ApiResponse(data=result)


@router.post("/xlsx")
async def http_generate_xlsx(
    body: GenerateXlsxRequest,
    user: User = Depends(require_permission("editor")),
):
    result = await _cap_xlsx(body.model_dump(), f"user:{user.id}")
    return ApiResponse(data=result)


@router.post("/pptx")
async def http_generate_pptx(
    body: GeneratePptxRequest,
    user: User = Depends(require_permission("editor")),
):
    result = await _cap_pptx(body.model_dump(), f"user:{user.id}")
    return ApiResponse(data=result)


@router.post("/pdf")
async def http_generate_pdf(
    body: GeneratePdfRequest,
    user: User = Depends(require_permission("editor")),
):
    result = await _cap_pdf(body.model_dump(), f"user:{user.id}")
    return ApiResponse(data=result)


@router.post("/convert")
async def http_convert(
    body: ConvertRequest,
    user: User = Depends(require_permission("editor")),
):
    result = await _cap_convert(body.model_dump(), f"user:{user.id}")
    return ApiResponse(data=result)
