// Auto-generated by scripts/scan-products.js — do not edit manually
// Run `npm run scan:products` or `npm run build` to regenerate

export interface GeneratedProductEntry {
  productId: string
  displayName: string
  entryComponentKey: string
  workspaceKind: string
  category: string
  icon: string
  legacyAppKeys: string[]
  fileAssociations: Array<Record<string, unknown>>
  createDocumentTypes: Array<Record<string, unknown>>
  windowPolicy: Record<string, unknown>
  activationPolicy: Record<string, unknown>
  visibility: Record<string, unknown>
  description: string
  uiContract: { kit: string; layout: string; shell?: unknown; feedback?: string; density?: string } | null
}

export const productCatalog: GeneratedProductEntry[] = [
  {
    "productId": "ai",
    "displayName": "AI",
    "entryComponentKey": "agent/index.vue",
    "workspaceKind": "ConversationWorkspace",
    "category": "ai",
    "icon": "ChatDotRound",
    "legacyAppKeys": [
      "agent"
    ],
    "fileAssociations": [],
    "createDocumentTypes": [],
    "windowPolicy": {
      "defaultWidth": 1080,
      "defaultHeight": 760,
      "singleton": false,
      "allowMultiple": true,
      "sortOrder": 50
    },
    "activationPolicy": {
      "default": "new-window"
    },
    "visibility": {
      "desktop": true,
      "launcher": true,
      "dock": true
    },
    "description": "智能体对话与工具编排",
    "uiContract": {
      "kit": "mac-app-v1",
      "layout": "chat",
      "shell": {
        "useAppWindowFrame": true,
        "sidebar": "required",
        "toolbar": "required",
        "statusbar": "none"
      },
      "feedback": "desktop-kit",
      "density": "comfortable"
    }
  },
  {
    "productId": "content-studio",
    "displayName": "内容工作室",
    "entryComponentKey": "products/content-studio/frontend/index.vue",
    "workspaceKind": "DocumentWorkspace",
    "category": "content",
    "icon": "Brush",
    "legacyAppKeys": [],
    "fileAssociations": [],
    "createDocumentTypes": [
      {
        "extension": "md",
        "label": "内容草稿",
        "contentType": "text"
      }
    ],
    "windowPolicy": {
      "defaultWidth": 1040,
      "defaultHeight": 740,
      "singleton": false,
      "allowMultiple": true,
      "sortOrder": 70
    },
    "activationPolicy": {
      "default": "new-window"
    },
    "visibility": {
      "desktop": true,
      "launcher": true,
      "dock": true
    },
    "description": "内容创作与发布编排入口",
    "uiContract": {
      "kit": "mac-app-v1",
      "layout": "document",
      "shell": {
        "useAppWindowFrame": true,
        "sidebar": "none",
        "toolbar": "required",
        "statusbar": "none"
      },
      "feedback": "desktop-kit",
      "density": "comfortable"
    }
  },
  {
    "productId": "files",
    "displayName": "文件",
    "entryComponentKey": "apps/desktop/index.vue",
    "workspaceKind": "CatalogWorkspace",
    "category": "files",
    "icon": "Folder",
    "legacyAppKeys": [
      "desktop"
    ],
    "fileAssociations": [
      {
        "associationId": "files.any",
        "contentTypes": [
          "*/*"
        ],
        "extensions": [
          "*"
        ],
        "mimeTypes": [
          "*/*"
        ],
        "modes": [
          "view"
        ],
        "adapterId": "files.browse",
        "priority": 10,
        "readOnlyFormats": []
      }
    ],
    "createDocumentTypes": [],
    "windowPolicy": {
      "defaultWidth": 1000,
      "defaultHeight": 700,
      "singleton": false,
      "allowMultiple": true,
      "sortOrder": 10
    },
    "activationPolicy": {
      "default": "reuse-tab"
    },
    "visibility": {
      "desktop": true,
      "launcher": true,
      "dock": true
    },
    "description": "桌面文件管理与资源浏览",
    "uiContract": {
      "kit": "mac-app-v1",
      "layout": "finder",
      "shell": {
        "useAppWindowFrame": true,
        "sidebar": "required",
        "toolbar": "required",
        "statusbar": "required"
      },
      "feedback": "desktop-kit",
      "density": "comfortable"
    }
  },
  {
    "productId": "knowledge",
    "displayName": "知识库",
    "entryComponentKey": "knowledge/index.vue",
    "workspaceKind": "CatalogWorkspace",
    "category": "knowledge",
    "icon": "Collection",
    "legacyAppKeys": [
      "knowledge"
    ],
    "fileAssociations": [],
    "createDocumentTypes": [],
    "windowPolicy": {
      "defaultWidth": 1100,
      "defaultHeight": 760,
      "singleton": true,
      "allowMultiple": false,
      "sortOrder": 40
    },
    "activationPolicy": {
      "default": "reuse-tab"
    },
    "visibility": {
      "desktop": true,
      "launcher": true,
      "dock": true
    },
    "description": "知识检索、画像与图谱",
    "uiContract": {
      "kit": "mac-app-v1",
      "layout": "finder",
      "shell": {
        "useAppWindowFrame": true,
        "sidebar": "required",
        "toolbar": "required",
        "statusbar": "none"
      },
      "feedback": "desktop-kit",
      "density": "comfortable"
    }
  },
  {
    "productId": "media",
    "displayName": "媒体",
    "entryComponentKey": "media-intelligence/index.vue",
    "workspaceKind": "MediaWorkspace",
    "category": "media",
    "icon": "Picture",
    "legacyAppKeys": [
      "media-intelligence",
      "image-viewer"
    ],
    "fileAssociations": [
      {
        "associationId": "media.image",
        "contentTypes": [
          "image/*"
        ],
        "extensions": [
          "png",
          "jpg",
          "jpeg",
          "gif",
          "webp",
          "bmp",
          "svg"
        ],
        "mimeTypes": [
          "image/*"
        ],
        "modes": [
          "view"
        ],
        "adapterId": "media.image",
        "priority": 80,
        "readOnlyFormats": []
      },
      {
        "associationId": "media.av",
        "contentTypes": [
          "audio/*",
          "video/*"
        ],
        "extensions": [
          "mp3",
          "wav",
          "aac",
          "ogg",
          "flac",
          "m4a",
          "mp4",
          "webm",
          "mov",
          "m4v"
        ],
        "mimeTypes": [
          "audio/*",
          "video/*"
        ],
        "modes": [
          "view"
        ],
        "adapterId": "media.av",
        "priority": 70,
        "readOnlyFormats": []
      }
    ],
    "createDocumentTypes": [],
    "windowPolicy": {
      "defaultWidth": 980,
      "defaultHeight": 700,
      "singleton": false,
      "allowMultiple": true,
      "sortOrder": 30
    },
    "activationPolicy": {
      "default": "new-window"
    },
    "visibility": {
      "desktop": true,
      "launcher": true,
      "dock": true
    },
    "description": "图片与音视频浏览/轻分析入口",
    "uiContract": {
      "kit": "mac-app-v1",
      "layout": "utility",
      "shell": {
        "useAppWindowFrame": true,
        "sidebar": "optional",
        "toolbar": "optional",
        "statusbar": "none"
      },
      "feedback": "desktop-kit",
      "density": "comfortable"
    }
  },
  {
    "productId": "messages",
    "displayName": "消息",
    "entryComponentKey": "im/index.vue",
    "workspaceKind": "ConversationWorkspace",
    "category": "messages",
    "icon": "ChatLineRound",
    "legacyAppKeys": [
      "im"
    ],
    "fileAssociations": [],
    "createDocumentTypes": [],
    "windowPolicy": {
      "defaultWidth": 1000,
      "defaultHeight": 720,
      "singleton": true,
      "allowMultiple": false,
      "sortOrder": 60
    },
    "activationPolicy": {
      "default": "reuse-tab"
    },
    "visibility": {
      "desktop": true,
      "launcher": true,
      "dock": true
    },
    "description": "即时消息与会话工作区",
    "uiContract": {
      "kit": "mac-app-v1",
      "layout": "chat",
      "shell": {
        "useAppWindowFrame": true,
        "sidebar": "required",
        "toolbar": "optional",
        "statusbar": "none"
      },
      "feedback": "desktop-kit",
      "density": "comfortable"
    }
  },
  {
    "productId": "office",
    "displayName": "Office",
    "entryComponentKey": "products/office/frontend/index.vue",
    "workspaceKind": "DocumentWorkspace",
    "category": "office",
    "icon": "Document",
    "legacyAppKeys": [
      "doc-viewer",
      "ppt-viewer",
      "pdf-viewer",
      "excel-engine",
      "docs-open"
    ],
    "fileAssociations": [
      {
        "associationId": "office.docx",
        "contentTypes": [
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        ],
        "extensions": [
          "docx",
          "doc"
        ],
        "mimeTypes": [
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "application/msword"
        ],
        "modes": [
          "view",
          "edit"
        ],
        "adapterId": "office.document",
        "priority": 100,
        "readOnlyFormats": [
          "doc"
        ]
      },
      {
        "associationId": "office.pptx",
        "contentTypes": [
          "application/vnd.openxmlformats-officedocument.presentationml.presentation"
        ],
        "extensions": [
          "pptx",
          "ppt"
        ],
        "mimeTypes": [
          "application/vnd.openxmlformats-officedocument.presentationml.presentation",
          "application/vnd.ms-powerpoint"
        ],
        "modes": [
          "view",
          "edit"
        ],
        "adapterId": "office.presentation",
        "priority": 100,
        "readOnlyFormats": [
          "ppt"
        ]
      },
      {
        "associationId": "office.xlsx",
        "contentTypes": [
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        ],
        "extensions": [
          "xlsx",
          "xls",
          "csv"
        ],
        "mimeTypes": [
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
          "application/vnd.ms-excel",
          "text/csv"
        ],
        "modes": [
          "view",
          "edit"
        ],
        "adapterId": "office.spreadsheet",
        "priority": 90,
        "readOnlyFormats": [
          "xls"
        ]
      },
      {
        "associationId": "office.pdf",
        "contentTypes": [
          "application/pdf"
        ],
        "extensions": [
          "pdf"
        ],
        "mimeTypes": [
          "application/pdf"
        ],
        "modes": [
          "view"
        ],
        "adapterId": "office.pdf",
        "priority": 100,
        "readOnlyFormats": [
          "pdf"
        ]
      }
    ],
    "createDocumentTypes": [
      {
        "extension": "docx",
        "label": "Word 文档",
        "contentType": "document"
      },
      {
        "extension": "pptx",
        "label": "演示文稿",
        "contentType": "presentation"
      },
      {
        "extension": "xlsx",
        "label": "工作簿",
        "contentType": "spreadsheet"
      }
    ],
    "windowPolicy": {
      "defaultWidth": 1100,
      "defaultHeight": 760,
      "singleton": false,
      "allowMultiple": true,
      "sortOrder": 20
    },
    "activationPolicy": {
      "default": "reuse-tab"
    },
    "visibility": {
      "desktop": true,
      "launcher": true,
      "dock": true
    },
    "description": "统一文档/表格/演示工作区",
    "uiContract": {
      "kit": "mac-app-v1",
      "layout": "document",
      "shell": {
        "useAppWindowFrame": true,
        "sidebar": "none",
        "toolbar": "required",
        "statusbar": "none"
      },
      "feedback": "desktop-kit",
      "density": "comfortable"
    }
  },
  {
    "productId": "recycle",
    "displayName": "回收站",
    "entryComponentKey": "apps/recycle/index.vue",
    "workspaceKind": "CatalogWorkspace",
    "category": "files",
    "icon": "Delete",
    "legacyAppKeys": [
      "recycle"
    ],
    "fileAssociations": [],
    "createDocumentTypes": [],
    "windowPolicy": {
      "defaultWidth": 900,
      "defaultHeight": 600,
      "singleton": true,
      "allowMultiple": false,
      "sortOrder": 11
    },
    "activationPolicy": {
      "default": "reuse-tab"
    },
    "visibility": {
      "desktop": true,
      "launcher": true,
      "dock": true
    },
    "description": "已删除文件恢复与清理",
    "uiContract": {
      "kit": "mac-app-v1",
      "layout": "finder",
      "shell": {
        "useAppWindowFrame": true,
        "sidebar": "required",
        "toolbar": "required",
        "statusbar": "required"
      },
      "feedback": "desktop-kit",
      "density": "comfortable"
    }
  },
  {
    "productId": "settings",
    "displayName": "设置",
    "entryComponentKey": "apps/settings/index.vue",
    "workspaceKind": "CatalogWorkspace",
    "category": "system",
    "icon": "Setting",
    "legacyAppKeys": [],
    "fileAssociations": [],
    "createDocumentTypes": [],
    "windowPolicy": {
      "defaultWidth": 860,
      "defaultHeight": 640,
      "singleton": true,
      "allowMultiple": false,
      "sortOrder": 90
    },
    "activationPolicy": {
      "default": "reuse-tab"
    },
    "visibility": {
      "desktop": true,
      "launcher": true,
      "dock": true
    },
    "description": "系统与个人偏好设置",
    "uiContract": {
      "kit": "mac-app-v1",
      "layout": "settings",
      "shell": {
        "useAppWindowFrame": true,
        "sidebar": "required",
        "toolbar": "required",
        "statusbar": "none"
      },
      "feedback": "desktop-kit",
      "density": "comfortable"
    }
  },
  {
    "productId": "text",
    "displayName": "文本",
    "entryComponentKey": "text-editor/index.vue",
    "workspaceKind": "DocumentWorkspace",
    "category": "text",
    "icon": "EditPen",
    "legacyAppKeys": [
      "text-editor"
    ],
    "fileAssociations": [
      {
        "associationId": "text.plain",
        "contentTypes": [
          "text/plain",
          "text/markdown"
        ],
        "extensions": [
          "txt",
          "md",
          "json",
          "yaml",
          "yml",
          "log",
          "csv"
        ],
        "mimeTypes": [
          "text/plain",
          "text/markdown",
          "application/json"
        ],
        "modes": [
          "view",
          "edit"
        ],
        "adapterId": "text.editor",
        "priority": 80,
        "readOnlyFormats": []
      }
    ],
    "createDocumentTypes": [
      {
        "extension": "txt",
        "label": "文本文档",
        "contentType": "text"
      },
      {
        "extension": "md",
        "label": "Markdown",
        "contentType": "text"
      }
    ],
    "windowPolicy": {
      "defaultWidth": 900,
      "defaultHeight": 640,
      "singleton": false,
      "allowMultiple": true,
      "sortOrder": 21
    },
    "activationPolicy": {
      "default": "new-tab"
    },
    "visibility": {
      "desktop": true,
      "launcher": true,
      "dock": true
    },
    "description": "纯文本与 Markdown 编辑",
    "uiContract": {
      "kit": "mac-app-v1",
      "layout": "document",
      "shell": {
        "useAppWindowFrame": true,
        "sidebar": "none",
        "toolbar": "required",
        "statusbar": "optional"
      },
      "feedback": "desktop-kit",
      "density": "comfortable"
    }
  }
]

export const productKeyMap: Record<string, GeneratedProductEntry> = Object.fromEntries(
  productCatalog.map((p) => [p.productId, p]),
)
