// Auto-generated by scripts/scan-products.js — do not edit manually
import type { Component } from 'vue'

export const productComponentKeyMap: Record<string, () => Promise<{ default: Component }>> = {
  'products/content-studio/frontend/index.vue': () => import('@products/content-studio/frontend/index.vue'),
  'products/office/frontend/index.vue': () => import('@products/office/frontend/index.vue'),
}
