#!/usr/bin/env node
// scan-modules.js
//
// Scans modules/*/manifest.json and generates the component-key-map.
// Build-time scan approach: Vite resolves @modules via alias (vite.config.ts)
// and includes module entries in the build automatically.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..', '..')
const MODULES_DIR = path.join(ROOT, 'modules')
const OUTPUT_FILE = path.join(
  ROOT, 'frontend', 'src', 'desktop', 'app-registry', 'component-key-map.generated.ts',
)

const entries = []

if (fs.existsSync(MODULES_DIR)) {
  for (const moduleName of fs.readdirSync(MODULES_DIR)) {
    const manifestPath = path.join(MODULES_DIR, moduleName, 'manifest.json')
    if (!fs.existsSync(manifestPath)) continue

    const stat = fs.statSync(path.join(MODULES_DIR, moduleName))
    if (!stat.isDirectory()) continue

    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'))
    const entryFile = manifest.component_key || 'entry.vue'
    const importPath = `@modules/${moduleName}/frontend/${entryFile}`

    entries.push({
      key: `${moduleName}/${entryFile}`,
      importPath,
      appName: manifest.name || moduleName,
    })
  }
}

const lines = [
  '// Auto-generated by scripts/scan-modules.js — do not edit manually',
  '// Run `npm run scan:modules` or `npm run build` to regenerate',
  '',
  'export const componentKeyMap: Record<string, () => Promise<{ default: any }>> = {',
]

for (const entry of entries) {
  lines.push(`  '${entry.key}': () => import('${entry.importPath}'),`)
}

lines.push('}')
lines.push('')

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true })
fs.writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf-8')
console.log(`[scan-modules] Generated ${entries.length} entries → ${OUTPUT_FILE}`)
