#!/usr/bin/env node
// scan-modules.js
//
// Scans modules/*/manifest.json and generates the component-key-map.
// Build-time scan approach: Vite resolves @modules via alias (vite.config.ts)
// and includes module entries in the build automatically.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..', '..')
const MODULES_DIR = path.join(ROOT, 'modules')
const WORKSPACES_DIR = path.join(ROOT, 'data', 'workspaces')
const COMPONENT_OUTPUT = path.join(
  ROOT, 'frontend', 'src', 'desktop', 'app-registry', 'component-key-map.generated.ts',
)
const ICON_OUTPUT = path.join(
  ROOT, 'frontend', 'src', 'shared', 'icons', 'module-icon-assets.generated.ts',
)

const entries = []
const iconEntries = []  // { moduleName, iconKey, iconAssetPath }

function scanPrivateModules() {
  if (!fs.existsSync(WORKSPACES_DIR)) return
  for (const userId of fs.readdirSync(WORKSPACES_DIR)) {
    if (userId.startsWith('.')) continue
    const pmDir = path.join(WORKSPACES_DIR, userId, 'private_modules')
    if (!fs.existsSync(pmDir)) continue
    for (const moduleName of fs.readdirSync(pmDir)) {
      if (moduleName.startsWith('_') || moduleName.startsWith('.')) continue
      const manifestPath = path.join(pmDir, moduleName, 'manifest.json')
      if (!fs.existsSync(manifestPath)) continue
      const stat = fs.statSync(path.join(pmDir, moduleName))
      if (!stat.isDirectory()) continue
      const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'))
      const entryFile = manifest.component_key || 'index.vue'
      const frontendFile = path.join(pmDir, moduleName, 'frontend', entryFile)
      if (!fs.existsSync(frontendFile)) continue
      const importPath = `@workspace/${userId}/private_modules/${moduleName}/frontend/${entryFile}`
      entries.push({
        key: `__private__${userId}__${moduleName}/${entryFile}`,
        importPath,
        appName: manifest.name || moduleName,
      })
      const iconAsset = (manifest.icon_asset || '').trim()
      if (iconAsset) {
        iconEntries.push({
          moduleName: `__private__${userId}__${moduleName}`,
          iconKey: manifest.icon || 'Collection',
          iconAssetPath: `@workspace/${userId}/private_modules/${moduleName}/frontend/${iconAsset}`,
        })
      }
    }
  }
}

if (fs.existsSync(MODULES_DIR)) {
  for (const moduleName of fs.readdirSync(MODULES_DIR)) {
    // Skip template and hidden directories
    if (moduleName.startsWith('_') || moduleName.startsWith('.')) continue

    const manifestPath = path.join(MODULES_DIR, moduleName, 'manifest.json')
    if (!fs.existsSync(manifestPath)) continue

    const stat = fs.statSync(path.join(MODULES_DIR, moduleName))
    if (!stat.isDirectory()) continue

    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'))
    const entryFile = manifest.component_key || 'index.vue'
    const frontendFile = path.join(MODULES_DIR, moduleName, 'frontend', entryFile)

    // 跳过无前端目录的后台模块（如 codemap）
    if (!fs.existsSync(frontendFile)) continue

    const importPath = `@modules/${moduleName}/frontend/${entryFile}`

    entries.push({
      key: `${moduleName}/${entryFile}`,
      importPath,
      appName: manifest.name || moduleName,
    })

    // Collect module icon assets
    const iconAsset = (manifest.icon_asset || '').trim()
    if (iconAsset) {
      iconEntries.push({
        moduleName,
        iconKey: manifest.icon || 'Collection',
        iconAssetPath: `@modules/${moduleName}/frontend/${iconAsset}`,
      })
    }
  }
}

// Scan private modules from user workspaces
scanPrivateModules()

// ── Generate component-key-map ──────────────────────────────────────
const compLines = [
  '// Auto-generated by scripts/scan-modules.js — do not edit manually',
  '// Run `npm run scan:modules` or `npm run build` to regenerate',
  '',
  'import type { Component } from \'vue\'',
  '',
  'export const componentKeyMap: Record<string, () => Promise<{ default: Component }>> = {',
]

for (const entry of entries) {
  compLines.push(`  '${entry.key}': () => import('${entry.importPath}'),`)
}

compLines.push('}')
compLines.push('')

fs.mkdirSync(path.dirname(COMPONENT_OUTPUT), { recursive: true })
fs.writeFileSync(COMPONENT_OUTPUT, compLines.join('\n'), 'utf-8')
console.log(`[scan-modules] Generated ${entries.length} component entries → ${COMPONENT_OUTPUT}`)

// ── Generate module-icon-assets ─────────────────────────────────────
const iconLines = [
  '// Auto-generated by scripts/scan-modules.js — do not edit manually',
  '// Run `npm run scan:modules` or `npm run build` to regenerate',
  '',
]

const iconImports = []
for (const ie of iconEntries) {
  const varName = `_icon_${ie.moduleName.replace(/-/g, '_')}`
  iconImports.push(`import ${varName} from '${ie.iconAssetPath}'`)
  iconLines.push(`import ${varName} from '${ie.iconAssetPath}'`)
}

iconLines.push('')
iconLines.push('export const moduleIconAssets: Record<string, string> = {')

for (let i = 0; i < iconEntries.length; i++) {
  const ie = iconEntries[i]
  const varName = `_icon_${ie.moduleName.replace(/-/g, '_')}`
  iconLines.push(`  '${ie.iconKey}': ${varName},`)
}

iconLines.push('}')
iconLines.push('')

fs.mkdirSync(path.dirname(ICON_OUTPUT), { recursive: true })
fs.writeFileSync(ICON_OUTPUT, iconLines.join('\n'), 'utf-8')
console.log(`[scan-modules] Generated ${iconEntries.length} module icon entries → ${ICON_OUTPUT}`)
