export const symbolIcons = {
  search: '⌕',
  catalog: '▦',
  taskProgress: '↻',
  evidenceChain: '◎',
  dictionary: '◇',
  pending: '✓',
  qualityEvaluation: '◉',
  rightSidebar: '⌖',
  refresh: '↻',
  minimizeAll: '▁',
  restoreAll: '□',
  fileManager: '▣',
  recycleBin: '⌫',
  feedback: '✉',
  user: '◉',
  settings: '⚙',
  logout: '⇥',
  view: '⊞',
  list: '≣',
  icon: '▦',
  sort: '⇅',
  add: '+',
  upload: '↑',
  folder: '▣',
  detail: 'ⓘ',
  open: '↗',
  more: '⋯',
  download: '↓',
  copy: '⎘',
  rename: '✎',
  delete: '⌫',
  clear: '⌧',
  restore: '↩',
  windowPreview: '▤',
  alignGrid: '⌗',
  autoArrange: '⋮',
  startMenu: '⊞',
  task: '✓',
} as const

export type SymbolIconKey = keyof typeof symbolIcons

export function getSymbolIcon(key: SymbolIconKey): string {
  return symbolIcons[key]
}
