"""add_required_permission_to_apps

Revision ID: 61a3a2d759d1
Revises: a5c5c617d91e
Create Date: 2026-06-15 01:32:10.277584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a3a2d759d1'
down_revision: Union[str, Sequence[str], None] = 'a5c5c617d91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('required_permission', sa.String(length=64), nullable=True, comment='Fine-grained permission key, e.g. knowledge:delete'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'required_permission')
    # ### end Alembic commands ###
