"""create_users_and_apps_tables

Revision ID: a5c5c617d91e
Revises: 
Create Date: 2026-06-15 01:28:56.996653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c5c617d91e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False, comment='Unique identifier, e.g. knowledge, agent'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Display name'),
    sa.Column('icon', sa.String(length=64), nullable=False, comment='Element Plus icon name'),
    sa.Column('description', sa.Text(), nullable=True, comment='App description'),
    sa.Column('route_prefix', sa.String(length=64), nullable=False, comment='API route prefix'),
    sa.Column('component_key', sa.String(length=128), nullable=False, comment='Frontend component key'),
    sa.Column('permissions', sa.JSON(), nullable=False, comment='Allowed roles: list of role names'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Display order, ascending'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether to show on desktop'),
    sa.Column('default_width', sa.Integer(), nullable=False),
    sa.Column('default_height', sa.Integer(), nullable=False),
    sa.Column('singleton', sa.Boolean(), nullable=False),
    sa.Column('resizable', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False, comment='Grouping category'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False, comment='Login username'),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='Bcrypt password hash'),
    sa.Column('display_name', sa.String(length=128), nullable=False, comment='Display name'),
    sa.Column('role', sa.String(length=32), nullable=False, comment='admin / editor / viewer'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether account is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('apps')
    # ### end Alembic commands ###
