"""add_recycle_knowledge_and_user_tables

Revision ID: cf5dee2fe584
Revises: d79ddd6b00e1
Create Date: 2026-06-15 01:35:43.185210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'cf5dee2fe584'
down_revision: Union[str, Sequence[str], None] = 'd79ddd6b00e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False, comment='Original file name'),
    sa.Column('file_path', sa.String(length=1024), nullable=False, comment='Storage path'),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False, comment='pending/processing/done/failed'),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update time'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recycle_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=False, comment='Original file/folder id'),
    sa.Column('item_type', sa.String(length=16), nullable=False, comment='file or folder'),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='Text content of the chunk'),
    sa.Column('embedding', Vector(dim=1024), nullable=True, comment='bge-m3 embedding vector'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Page number, position, etc.'),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update time'),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunks')
    op.drop_table('recycle_items')
    op.drop_table('catalogs')
    # ### end Alembic commands ###
