"""add_creatable_formats

Revision ID: d5dc41a139ab
Revises: 8e1316f7a8dc
Create Date: 2026-06-18 00:47:43.932326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5dc41a139ab'
down_revision: Union[str, Sequence[str], None] = '8e1316f7a8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('framework_app_registry', sa.Column('creatable_formats', sa.JSON(), nullable=True, comment='Creatable file type declarations'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('framework_app_registry', 'creatable_formats')
    # ### end Alembic commands ###
