"""create_folders_and_files_tables

Revision ID: d79ddd6b00e1
Revises: 61a3a2d759d1
Create Date: 2026-06-15 01:33:58.515725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd79ddd6b00e1'
down_revision: Union[str, Sequence[str], None] = '61a3a2d759d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False, comment='Folder name'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='Parent folder id, null=root'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='Creator'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update time'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False, comment='File name without extension'),
    sa.Column('extension', sa.String(length=32), nullable=False, comment='File extension, e.g. txt, pdf'),
    sa.Column('size', sa.BigInteger(), nullable=False, comment='File size in bytes'),
    sa.Column('folder_id', sa.Integer(), nullable=True, comment='Parent folder'),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False, comment='Path on disk relative to storage root'),
    sa.Column('mime_type', sa.String(length=128), nullable=False, comment='MIME type'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update time'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('folders')
    # ### end Alembic commands ###
